# Generated by Django 6.0 on 2026-01-08 07:21

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fichier_image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('text', 'Texte'), ('audio', 'Audio'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
