# Generated by Django 6.0 on 2026-01-08 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_fichier_image_alter_message_type_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonMasque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_masque', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masque_par', to='chat.salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons_masques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salon masqué',
                'verbose_name_plural': 'Salons masqués',
                'unique_together': {('user', 'salon')},
            },
        ),
    ]
